### ISSUE TITLE
Hand-written opam file for ntl uses dune incorrectly

### ISSUE THREAD

**Issue by sim642** [zkincaid/sv-opam#1]
When installing ntl from this opam repository for duet into a _local_ opam switch, the installation of the ntl package fails:
```
simmo@roentgenium:~/Desktop/duet/duet/_opam/.opam-switch/build/ntl.20200321 (modern)$ dune install
Entering directory '/home/simmo/Desktop/duet/duet'
Error: The following <package>.install are missing:
- _build/default/duet.install
- _build/default/pa.install
- _build/default/srk/srk.install
Hint: try running: dune build @install
```
The problem is that the _hand-written_ opam file for it uses dune incorrectly here:
https://github.com/zkincaid/sv-opam/blob/265313b7291d2950851f32a2f1c4a393d07d273b/packages/ntl/ntl.20200321/opam#L8-L10

Namely, this call of `dune install` will also find the dune-project file above in the filesystem and execute it there instead of the build directory of the local opam switch. A correct call of dune via opam needs to use `--root` or really just `-p` (which contains the former) to prevent the automatic detection of uppermost dune project. As-is, installation of ntl escapes its build directory, which it definitely should not.

Even though this is fixable with an additional `-p` argument, the correct way would be to replace hand-written opam files with ones generated by dune itself: https://dune.readthedocs.io/en/stable/opam.html#generating-opam-files. That guarantees that the opam file calls dune correctly.
Weirdly, ntl's own dune-project and opam file are completely empty: https://github.com/zkincaid/ocaml-ntl/tree/modern. Which is why I'm opening the issue here, where the incorrect command is given, instead of on ntl itself.

**Comment by zkincaid** [comment]
Thanks for the heads up.  Switched to the auto-generated .opam file.
